INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('1','Lady Representative - 1','All','0','F','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('2','Lady Representative - 2','All','0','F','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('3','UUC - 2','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('4','UUC - 1','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('6','Magazine Editor','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('7','Arts Club Secretary','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('8','General Secretary','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('9','Vice Chairman','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('10','Chairman','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('12','Second Year Representative','All','2','All','B');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('13','Third Year Representative','All','3','All','B');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('14','Fourth Year Representative','All','4','All','B');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('17','Production Association Secretary','P','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('11','First Year Representative','All','1','All','B');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('18','BT Association Secretary','B','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('19','CS Association Secretary','R','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('20','EC Association Secretary','T','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('22','Second Year MTech Representative','All','2','All','M');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('21','First Year MTech Representative','All','1','All','M');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('5','Sports Club Secretary','All','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('16','Automobile Association Secretary','A','0','All','All');
INSERT INTO "public"."poll_position" ("id","position","department","year","sex","degree") VALUES ('15','Mechanical Association Secretary','M','0','All','All');