INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('8','270163','','Sambhu C','21');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('9','270164','','Abhilash J J','19');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('10','270165','','Abhirami S A','20');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('11','270166','','Meghana Sarat','18');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('12','270167','','Thanush N S','17');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('13','270168','','Vishal V','16');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('14','270169','','Abhishek S','15');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('15','270170','','Swaraj K','12');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('16','270171','','Ampadi Krishnan V P','13');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('17','270172','','Rameez A S','14');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('18','270173','','Abin Sabu Mohamed','11');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('19','270174','','Akash Ashokan','10');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('21','270175','','Anandhu Chandran','8');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('22','270176','','Arun Kumar U','7');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('23','270177','','Niel George Varghese','6');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('20','270178','','Aiswarya S V','9');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('24','270179','','Nilshad N L','4');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('25','270180','','Sreehari Ramachandran','3');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('26','270181','','Gayatri S Kumar','1');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('27','270182','','Hitha Krishnan','2');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('28','270183','','Ajayanth B','22');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('29','270184','','Shatath Krishnan S','5');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('30','370163','','Varun J John','10');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('31','370164','','Parvathy B','9');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('32','370165','','Anantha Krishnan KS','7');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('33','370166','','A Anujith','6');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('34','370167','','Sujith S','8');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('35','370168','','Akhil Eldho','5');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('36','370169','','Harikrishnan V','4');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('37','370170','','Abhin Sunny Mathew','3');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('38','370171','','Anu K','1');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('39','370172','','Keerthi AS','2');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('40','370173','','Muhammed Ashkar','19');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('41','370174','','Haleel Rahuman','11');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('42','370175','','Joseph Jose','15');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('43','370176','','Keshav Jayashankar','18');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('44','370177','','Midhun A','17');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('45','370178','','Nivin Joy','13');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('46','370179','','Raoof Noushad','20');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('47','370180','','Sandeep Thomas','16');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('48','370181','','Varun G','12');
INSERT INTO "public"."poll_candidate" ("id","admission_no","image","name","post_id") VALUES ('49','370182','','Zacharia Joseph','14');