# Generated by Django 2.2.5 on 2020-01-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Candidate'),
        ),
    ]
